steps:

# Build docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/sotf-6/cicd-demo', '-f', './Dockerfile.prod', '.']

# Push the container to the registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/sotf-6/cicd-demo']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'gcr.io/sotf-6/cicd-demo'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
  - 'gcr.io/sotf-6/cicd-demo'