version: '3.7'

services:
  inspiration-fe-develop:
    container_name: inspiration-fe-develop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true